"""initial schema

Revision ID: ead34e2d0007
Revises: 
Create Date: 2026-06-18 23:52:30.638287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ead34e2d0007'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('classified_intent', sa.String(length=50), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('selected_agent', sa.String(length=100), nullable=True),
    sa.Column('response_summary', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=True),
    sa.Column('resource_type', sa.String(length=100), nullable=True),
    sa.Column('resource_id', sa.String(length=100), nullable=True),
    sa.Column('details_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_event_type'), 'audit_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_request_id'), 'audit_logs', ['request_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_id'), 'audit_logs', ['resource_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_type'), 'audit_logs', ['resource_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('source_path', sa.String(length=500), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filename')
    )
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_table('hr_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('intent', sa.String(length=50), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('selected_agent', sa.String(length=100), nullable=True),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hr_requests_id'), 'hr_requests', ['id'], unique=False)
    op.create_index(op.f('ix_hr_requests_request_id'), 'hr_requests', ['request_id'], unique=True)
    op.create_index(op.f('ix_hr_requests_user_id'), 'hr_requests', ['user_id'], unique=False)
    op.create_table('long_term_memory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('significance_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_accessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_long_term_memory_id'), 'long_term_memory', ['id'], unique=False)
    op.create_index(op.f('ix_long_term_memory_user_id'), 'long_term_memory', ['user_id'], unique=False)
    op.create_table('short_term_memory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('intent', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_short_term_memory_id'), 'short_term_memory', ['id'], unique=False)
    op.create_index(op.f('ix_short_term_memory_user_id'), 'short_term_memory', ['user_id'], unique=False)
    op.create_table('agent_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.String(length=100), nullable=False),
    sa.Column('agent_name', sa.String(length=100), nullable=False),
    sa.Column('input_summary', sa.Text(), nullable=True),
    sa.Column('output_summary', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('pii_redaction_counts', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['hr_requests.request_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_runs_id'), 'agent_runs', ['id'], unique=False)
    op.create_index(op.f('ix_agent_runs_request_id'), 'agent_runs', ['request_id'], unique=False)
    op.create_table('document_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('token_estimate', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_chunks_document_id'), 'document_chunks', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_chunks_id'), 'document_chunks', ['id'], unique=False)
    op.create_table('email_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.String(length=100), nullable=False),
    sa.Column('sender_email', sa.String(length=255), nullable=False),
    sa.Column('sender_name', sa.String(length=255), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('linked_request_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['linked_request_id'], ['hr_requests.request_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_events_event_id'), 'email_events', ['event_id'], unique=True)
    op.create_index(op.f('ix_email_events_id'), 'email_events', ['id'], unique=False)
    op.create_index(op.f('ix_email_events_linked_request_id'), 'email_events', ['linked_request_id'], unique=False)
    op.create_index(op.f('ix_email_events_sender_email'), 'email_events', ['sender_email'], unique=False)
    op.create_table('draft_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('draft_id', sa.String(length=100), nullable=False),
    sa.Column('request_id', sa.String(length=100), nullable=False),
    sa.Column('email_event_id', sa.String(length=100), nullable=True),
    sa.Column('recipient_email', sa.String(length=255), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('review_action', sa.String(length=50), nullable=False),
    sa.Column('review_required', sa.Boolean(), nullable=False),
    sa.Column('review_priority', sa.String(length=50), nullable=False),
    sa.Column('review_reason', sa.Text(), nullable=False),
    sa.Column('review_decision_source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['email_event_id'], ['email_events.event_id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['hr_requests.request_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_draft_responses_draft_id'), 'draft_responses', ['draft_id'], unique=True)
    op.create_index(op.f('ix_draft_responses_email_event_id'), 'draft_responses', ['email_event_id'], unique=False)
    op.create_index(op.f('ix_draft_responses_id'), 'draft_responses', ['id'], unique=False)
    op.create_index(op.f('ix_draft_responses_request_id'), 'draft_responses', ['request_id'], unique=False)
    op.create_table('request_policy_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.String(length=100), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('document_title', sa.String(length=255), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('chunk_id', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['document_chunks.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['hr_requests.request_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_request_policy_sources_chunk_id'), 'request_policy_sources', ['chunk_id'], unique=False)
    op.create_index(op.f('ix_request_policy_sources_document_id'), 'request_policy_sources', ['document_id'], unique=False)
    op.create_index(op.f('ix_request_policy_sources_id'), 'request_policy_sources', ['id'], unique=False)
    op.create_index(op.f('ix_request_policy_sources_request_id'), 'request_policy_sources', ['request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_request_policy_sources_request_id'), table_name='request_policy_sources')
    op.drop_index(op.f('ix_request_policy_sources_id'), table_name='request_policy_sources')
    op.drop_index(op.f('ix_request_policy_sources_document_id'), table_name='request_policy_sources')
    op.drop_index(op.f('ix_request_policy_sources_chunk_id'), table_name='request_policy_sources')
    op.drop_table('request_policy_sources')
    op.drop_index(op.f('ix_draft_responses_request_id'), table_name='draft_responses')
    op.drop_index(op.f('ix_draft_responses_id'), table_name='draft_responses')
    op.drop_index(op.f('ix_draft_responses_email_event_id'), table_name='draft_responses')
    op.drop_index(op.f('ix_draft_responses_draft_id'), table_name='draft_responses')
    op.drop_table('draft_responses')
    op.drop_index(op.f('ix_email_events_sender_email'), table_name='email_events')
    op.drop_index(op.f('ix_email_events_linked_request_id'), table_name='email_events')
    op.drop_index(op.f('ix_email_events_id'), table_name='email_events')
    op.drop_index(op.f('ix_email_events_event_id'), table_name='email_events')
    op.drop_table('email_events')
    op.drop_index(op.f('ix_document_chunks_id'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_document_id'), table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index(op.f('ix_agent_runs_request_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_id'), table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_index(op.f('ix_short_term_memory_user_id'), table_name='short_term_memory')
    op.drop_index(op.f('ix_short_term_memory_id'), table_name='short_term_memory')
    op.drop_table('short_term_memory')
    op.drop_index(op.f('ix_long_term_memory_user_id'), table_name='long_term_memory')
    op.drop_index(op.f('ix_long_term_memory_id'), table_name='long_term_memory')
    op.drop_table('long_term_memory')
    op.drop_index(op.f('ix_hr_requests_user_id'), table_name='hr_requests')
    op.drop_index(op.f('ix_hr_requests_request_id'), table_name='hr_requests')
    op.drop_index(op.f('ix_hr_requests_id'), table_name='hr_requests')
    op.drop_table('hr_requests')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_request_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_event_type'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
